POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Test Blog",
    "author": "Archie beales",
    "url": "http://someurl.com",
    "likes" : 0,
    "user": "62c6a5f38e4ba2688706cc6a"
}